--NOMBRES DE TIPOS DE ACTIVIDADES EN FUNCION A UN PACIENTE

INSERT INTO dbo.ActividadesTipo VALUES('PACIENTE SE INSTITUCIONALIZA','', 'P')--SE DEBE ACTUALIZA TANTO EN LA FICHA SOCIAL COMO EN EL REGISTRO DE REINGRESO
INSERT INTO dbo.ActividadesTipo VALUES('PACIENTE SE DES-INSTITUCIONALIZA','', 'P')--SE DEBE ACTUALIZA TANTO EN LA FICHA SOCIAL COMO EN EL REGISTRO DE REINGRESO
INSERT INTO dbo.ActividadesTipo VALUES('REGISTRO DE FICHA SOCIAL O REINGRESO','') 
INSERT INTO dbo.ActividadesTipo VALUES('INFORMACIÓN Y ORIENTACIÓN A PACIENTES Y/O FAMILIARES','')
INSERT INTO dbo.ActividadesTipo VALUES('PACIENTE RECIBE VISITA','')
INSERT INTO dbo.ActividadesTipo VALUES('ENTREVISTA CON PACIENTES','')
INSERT INTO dbo.ActividadesTipo VALUES('ENTREVISTA CON FAMILIARES Y/O RESPONSABLES','')
INSERT INTO dbo.ActividadesTipo VALUES('VISITA DOMICILIARIA E INSTITUCIONAL','')
INSERT INTO dbo.ActividadesTipo VALUES('TRAMITE DE DOCUMENTOS PERSONALES DEL PACIENTE','','P')--SE ABRIRA EL FORMULARIO DE DOC
INSERT INTO dbo.ActividadesTipo VALUES('OTRO TIPO DE TRÁMITES','')
INSERT INTO dbo.ActividadesTipo VALUES('RECEPCIÓN DE ENCOMIENDA','')
INSERT INTO dbo.ActividadesTipo VALUES('COMUNICACIÓN VIA TELEFÓNICA','')
INSERT INTO dbo.ActividadesTipo VALUES('GESTIÓN DE RECETAS, LABORATORIOS U OTROS ESTUDIOS','')
INSERT INTO dbo.ActividadesTipo VALUES('GESTIÓN PARA ATENCIÓN DE PACIENTES EN OTROS CENTROS HOSPITALARIOS','')
INSERT INTO dbo.ActividadesTipo VALUES('COORDINACIÓN INTERINSTITUCIONAL','')
INSERT INTO dbo.ActividadesTipo VALUES('COORDINACIÓN INTRAINSTITUCIONAL','') 
INSERT INTO dbo.ActividadesTipo VALUES('PERMISO O VACACIÓN DEL PACIENTE','')
INSERT INTO dbo.ActividadesTipo VALUES('REINCORPORACIÓN DEL PACIENTE','')
INSERT INTO dbo.ActividadesTipo VALUES('EVACIÓN O FUGA','')
INSERT INTO dbo.ActividadesTipo VALUES('ALTA','')--SE CONSIDERA DES-INSTITUCIONALIZADO
INSERT INTO dbo.ActividadesTipo VALUES('DEFUNCIÓN','')--SE CONSIDERA DES-INSTITUCIONALIZADO
INSERT INTO dbo.ActividadesTipo VALUES('REUNIÓN CON EQUIPO DE UNIDADES','')
INSERT INTO dbo.ActividadesTipo VALUES('REUNIÓN CON JEFE DE SALA, DIRECTOR MÉDICO, ADMINISTRATIVO U OTROS SERVICIOS','')
INSERT INTO dbo.ActividadesTipo VALUES('OTRAS ACTIVIDADES','')


--NOMBRES DE TIPOS DE ACTIVIDADES SOBRE ACTIVIDADES ADMINISTRATIVAS

INSERT INTO dbo.ActividadesTipo VALUES('INFORMACIÓN Y ORIENTACIÓN A PACIENTES Y/O FAMILIARES','')
INSERT INTO dbo.ActividadesTipo VALUES('ASISTENCIA A CONFERENCIAS DE CAPACITACIÓN','')
INSERT INTO dbo.ActividadesTipo VALUES('SESIÓN CLÍNICA','')
INSERT INTO dbo.ActividadesTipo VALUES('DOCENCIA ASISTENCIAL','')
INSERT INTO dbo.ActividadesTipo VALUES('OTRAS ACTIVIDADES','')
SELECT * FROM ActividadesTipo