--PAISES

INSERT INTO Paises(CodigoPais, NombrePais) VALUES('BO', 'BOLIVIA')


--DEPARTAMENTOS
INSERT INTO Departamentos VALUES('BO','01','CHUQUISACA')
INSERT INTO Departamentos VALUES('BO','02','LA PAZ')
INSERT INTO Departamentos VALUES('BO','03','COCHABAMBA')
INSERT INTO Departamentos VALUES('BO','04','ORURO')
INSERT INTO Departamentos VALUES('BO','05','POTOSÍ')
INSERT INTO Departamentos VALUES('BO','06','TARIJA')
INSERT INTO Departamentos VALUES('BO','07','SANTA CRUZ')
INSERT INTO Departamentos VALUES('BO','08','BENI')
INSERT INTO Departamentos VALUES('BO','09','PANDO')

--PROVINCIAS DE CHUQUISACA
INSERT INTO Provincias VALUES('BO','01','01','OROPEZA')
INSERT INTO Provincias VALUES('BO','01','02','AZURDUY')
INSERT INTO Provincias VALUES('BO','01','03','JAIME ZUDAÑEZ')
INSERT INTO Provincias VALUES('BO','01','04','TOMINA')
INSERT INTO Provincias VALUES('BO','01','05','HERNANDO SILES')
INSERT INTO Provincias VALUES('BO','01','06','YAMPARAEZ')
INSERT INTO Provincias VALUES('BO','01','07','NOR CINTI')
INSERT INTO Provincias VALUES('BO','01','08','SUR CINTI')
INSERT INTO Provincias VALUES('BO','01','09','BELISARIO BOETO')
INSERT INTO Provincias VALUES('BO','01','10','LUIS CALVO')

--PROVINCIAS DE LA PAZ
INSERT INTO Provincias VALUES('BO','02','01','AROMA')
INSERT INTO Provincias VALUES('BO','02','02','BAUTISTA SAAVEDRA')
INSERT INTO Provincias VALUES('BO','02','03','ABEL ITURRALDE')
INSERT INTO Provincias VALUES('BO','02','04','CARANAVI')
INSERT INTO Provincias VALUES('BO','02','05','ELIODORO CAMACHO')
INSERT INTO Provincias VALUES('BO','02','06','FRANZ TAMAYO')
INSERT INTO Provincias VALUES('BO','02','07','GUALBERTO VILLAROEL')
INSERT INTO Provincias VALUES('BO','02','08','INGAVI')
INSERT INTO Provincias VALUES('BO','02','09','INQUISIVI')
INSERT INTO Provincias VALUES('BO','02','10','JOSÉ MANUEL PANDO')
INSERT INTO Provincias VALUES('BO','02','11','LARECAJA')
INSERT INTO Provincias VALUES('BO','02','12','JOSE RAMÓN LOAYZA')
INSERT INTO Provincias VALUES('BO','02','13','LOS ANDES')
INSERT INTO Provincias VALUES('BO','02','14','MANCO KAPAC')
INSERT INTO Provincias VALUES('BO','02','15','ILDEFONSO ESTANISLAO DE LAS MUÑECAS')
INSERT INTO Provincias VALUES('BO','02','16','NOR YUNGAS')
INSERT INTO Provincias VALUES('BO','02','17','OMASUYOS')
INSERT INTO Provincias VALUES('BO','02','18','PACAJES')
INSERT INTO Provincias VALUES('BO','02','19','PEDRO DOMINGO MURILLO')
INSERT INTO Provincias VALUES('BO','02','20','SUD YUNGAS')

--PROVINCIAS DE COCHABAMBA
INSERT INTO Provincias VALUES('BO','03','01','ARANI')
INSERT INTO Provincias VALUES('BO','03','02','ESTEBAN ARZE')
INSERT INTO Provincias VALUES('BO','03','03','ARQUE')
INSERT INTO Provincias VALUES('BO','03','04','AYOPAYA')
INSERT INTO Provincias VALUES('BO','03','05','CAMPERO')
INSERT INTO Provincias VALUES('BO','03','06','CAPINOTA')
INSERT INTO Provincias VALUES('BO','03','07','CERCADO')
INSERT INTO Provincias VALUES('BO','03','08','CARRASCO')
INSERT INTO Provincias VALUES('BO','03','09','CHAPARE')
INSERT INTO Provincias VALUES('BO','03','10','GERMÁN JORDÁN')
INSERT INTO Provincias VALUES('BO','03','11','MIZQUE')
INSERT INTO Provincias VALUES('BO','03','12','PUNATA')
INSERT INTO Provincias VALUES('BO','03','13','QUILLACOLLO')
INSERT INTO Provincias VALUES('BO','03','14','TAPACARÍ')
INSERT INTO Provincias VALUES('BO','03','15','BOLÍVAR')
INSERT INTO Provincias VALUES('BO','03','16','TIRAQUE')


--PROVINCIAS DE ORURO
INSERT INTO Provincias VALUES('BO','04','01','ATAHUALLPA')
INSERT INTO Provincias VALUES('BO','04','02','CARANGAS')
INSERT INTO Provincias VALUES('BO','04','03','CERCADO')
INSERT INTO Provincias VALUES('BO','04','04','EDUARDO AVAROA')
INSERT INTO Provincias VALUES('BO','04','05','LADISLAO CABRERA')
INSERT INTO Provincias VALUES('BO','04','06','LITORAL')
INSERT INTO Provincias VALUES('BO','04','07','PUERTO DE MEJILLONES')
INSERT INTO Provincias VALUES('BO','04','08','NOR CARANGAS')
INSERT INTO Provincias VALUES('BO','04','09','PANTALEÓN DALENCE')
INSERT INTO Provincias VALUES('BO','04','10','POOPÓ')
INSERT INTO Provincias VALUES('BO','04','11','SAJAMA')
INSERT INTO Provincias VALUES('BO','04','12','SAN PEDRO DE TOTORA')
INSERT INTO Provincias VALUES('BO','04','13','SAUCARÍ')
INSERT INTO Provincias VALUES('BO','04','14','SEBASTIAN PAGADOR')
INSERT INTO Provincias VALUES('BO','04','15','SUD CARANGAS')
INSERT INTO Provincias VALUES('BO','04','16','TOMAS BARRÓN')


--PROVINCIAS DE POTOSÍ
INSERT INTO Provincias VALUES('BO','05','01','ALONSO DE IBÁÑEZ')
INSERT INTO Provincias VALUES('BO','05','02','ANTONIO QUIJARRO')
INSERT INTO Provincias VALUES('BO','05','03','BERNARDINO BILBAO')
INSERT INTO Provincias VALUES('BO','05','04','CHARCAS')
INSERT INTO Provincias VALUES('BO','05','05','CHAYANTA')
INSERT INTO Provincias VALUES('BO','05','06','CORNELIO SAAVEDRA')
INSERT INTO Provincias VALUES('BO','05','07','DANIEL CAMPOS')
INSERT INTO Provincias VALUES('BO','05','08','ENRIQUE BALDIVIESO')
INSERT INTO Provincias VALUES('BO','05','09','JOSÉ MARÍA LINARES')
INSERT INTO Provincias VALUES('BO','05','10','MODESTO OMISTE')
INSERT INTO Provincias VALUES('BO','05','11','NOR CHICHAS')
INSERT INTO Provincias VALUES('BO','05','12','NOR LÍPEZ')
INSERT INTO Provincias VALUES('BO','05','13','RAFAEL BUSTILLO ')
INSERT INTO Provincias VALUES('BO','05','14','SUD CHICHAS')
INSERT INTO Provincias VALUES('BO','05','15','SUD LÍPEZ')
INSERT INTO Provincias VALUES('BO','05','16','TOMÁS FRÍAS')

--PROVINCIAS DE TARIJA
INSERT INTO Provincias VALUES('BO','06','01','ANICETO ARCE')
INSERT INTO Provincias VALUES('BO','06','02','BURDET OCONNOR')
INSERT INTO Provincias VALUES('BO','06','03','CERCADO ')
INSERT INTO Provincias VALUES('BO','06','04','EUSTAQUIO MÉNDEZ')
INSERT INTO Provincias VALUES('BO','06','05','GRAN CHACO')
INSERT INTO Provincias VALUES('BO','06','06','JOSÉ MARÍA AVILÉS')


--PROVINCIAS DE SANTA CRUZ
INSERT INTO Provincias VALUES('BO','07','01','ANDRÉS IBAÑEZ')
INSERT INTO Provincias VALUES('BO','07','02','ÁNGEL SALDÓVAL')
INSERT INTO Provincias VALUES('BO','07','03','CABALLERO')
INSERT INTO Provincias VALUES('BO','07','04','CHIQUITOS')
INSERT INTO Provincias VALUES('BO','07','05','CORDILLERA')
INSERT INTO Provincias VALUES('BO','07','06','FLORIDA')
INSERT INTO Provincias VALUES('BO','07','07','GERMÁN BUSCH')
INSERT INTO Provincias VALUES('BO','07','08','GUARAYOS')
INSERT INTO Provincias VALUES('BO','07','09','ICHILO')
INSERT INTO Provincias VALUES('BO','07','10','ÑUFLO DE CHAVES')
INSERT INTO Provincias VALUES('BO','07','11','OBISPO SANTISTEVAN ')
INSERT INTO Provincias VALUES('BO','07','12','SARA')
INSERT INTO Provincias VALUES('BO','07','13','VALLEGRANDE')
INSERT INTO Provincias VALUES('BO','07','14','VELASCO')
INSERT INTO Provincias VALUES('BO','07','15','WARNES')


--PROVINCIAS DE BENI
INSERT INTO Provincias VALUES('BO','08','01','CERCADO')
INSERT INTO Provincias VALUES('BO','08','02','ANTONIO VACA DÍEZ')
INSERT INTO Provincias VALUES('BO','08','03','GENERAL JOSÉ BALLIVIÁN SEGUROLA')
INSERT INTO Provincias VALUES('BO','08','04','YACUMA')
INSERT INTO Provincias VALUES('BO','08','05','MOXOS ')
INSERT INTO Provincias VALUES('BO','08','06','MARBÁN')
INSERT INTO Provincias VALUES('BO','08','07','MAMORÉ')
INSERT INTO Provincias VALUES('BO','08','08','ITÉNEZ')


--PROVINCIAS DE PANDO
INSERT INTO Provincias VALUES('BO','09','01','ABUNÁ')
INSERT INTO Provincias VALUES('BO','09','02','DEFERICO ROMÁN')
INSERT INTO Provincias VALUES('BO','09','03','MADRE DE DIOS')
INSERT INTO Provincias VALUES('BO','09','04','MANURIPI')
INSERT INTO Provincias VALUES('BO','09','05','NICOLÁS SUÁREZ')



--LOCALIDADES DE CHUQUISACA
INSERT INTO Localidades VALUES('BO','01','01','01','SUCRE')
INSERT INTO Localidades VALUES('BO','01','02','02','AZURDUY')
INSERT INTO Localidades VALUES('BO','01','03','03','ZUDAÑEZ')
INSERT INTO Localidades VALUES('BO','01','04','04','PADILLA')
INSERT INTO Localidades VALUES('BO','01','05','05','MONTEAGUDO')
INSERT INTO Localidades VALUES('BO','01','06','06','TARABUCO')
INSERT INTO Localidades VALUES('BO','01','07','07','CAMARGO')
INSERT INTO Localidades VALUES('BO','01','08','08','VILLA ABECIA')
INSERT INTO Localidades VALUES('BO','01','09','09','SERRANO')
INSERT INTO Localidades VALUES('BO','01','10','10','MUYUPAMPA')


--LOCALIDADES DE LA PAZ
INSERT INTO Localidades VALUES('BO','02','01','01','SICA SICA')
INSERT INTO Localidades VALUES('BO','02','02','02','CHARAZANI')
INSERT INTO Localidades VALUES('BO','02','03','03','IXIAMAS')
INSERT INTO Localidades VALUES('BO','02','04','04','CARANAVI')
INSERT INTO Localidades VALUES('BO','02','05','05','PUERTO ACOSTA')
INSERT INTO Localidades VALUES('BO','02','06','06','APOLO')
INSERT INTO Localidades VALUES('BO','02','07','07','SAN PEDRO CURAHUARA DE CARANGAS')
INSERT INTO Localidades VALUES('BO','02','08','08','VIACHA')
INSERT INTO Localidades VALUES('BO','02','09','09','INQUISIVI')
INSERT INTO Localidades VALUES('BO','02','10','10','SANTIAGO DE MACHACA')
INSERT INTO Localidades VALUES('BO','02','11','11','SORATA')
INSERT INTO Localidades VALUES('BO','02','12','12','LURIBAY')
INSERT INTO Localidades VALUES('BO','02','13','13','PUCARANI')
INSERT INTO Localidades VALUES('BO','02','14','14','COPACABANA')
INSERT INTO Localidades VALUES('BO','02','15','15','CHUMA')
INSERT INTO Localidades VALUES('BO','02','16','16','COROICO')
INSERT INTO Localidades VALUES('BO','02','17','17','ACHACACHI')
INSERT INTO Localidades VALUES('BO','02','18','18','CORO CORO')
INSERT INTO Localidades VALUES('BO','02','19','19','PALCA')
INSERT INTO Localidades VALUES('BO','02','20','10','CHULUMANI')

--LOCALIDADES DE COCHABAMBA
INSERT INTO Localidades VALUES('BO','03','01','01','ARANI')
INSERT INTO Localidades VALUES('BO','03','02','02','TARATA')
INSERT INTO Localidades VALUES('BO','03','03','03','ARQUE')
INSERT INTO Localidades VALUES('BO','03','04','04','INDEPENDENCIA')
INSERT INTO Localidades VALUES('BO','03','05','05','AIQUILE')
INSERT INTO Localidades VALUES('BO','03','06','06','VILLA CAPINOTA')
INSERT INTO Localidades VALUES('BO','03','07','07','COCHABAMBA')
INSERT INTO Localidades VALUES('BO','03','08','08','TOTORA')
INSERT INTO Localidades VALUES('BO','03','09','09','SACABA')
INSERT INTO Localidades VALUES('BO','03','10','10','CLIZA')
INSERT INTO Localidades VALUES('BO','03','11','11','MIZQUE')
INSERT INTO Localidades VALUES('BO','03','12','12','PUNATA')
INSERT INTO Localidades VALUES('BO','03','13','13','QUILLACOLLO')
INSERT INTO Localidades VALUES('BO','03','14','14','TAPACARÍ')
INSERT INTO Localidades VALUES('BO','03','15','15','BOLÍVAR')
INSERT INTO Localidades VALUES('BO','03','16','16','TIRAQUE')

--LOCALIDADES DE ORURO
INSERT INTO Localidades VALUES('BO','04','01','01','SABAYA')
INSERT INTO Localidades VALUES('BO','04','02','02','CORQUE')
INSERT INTO Localidades VALUES('BO','04','03','03','ORURO')
INSERT INTO Localidades VALUES('BO','04','04','04','CHALLAPATA')
INSERT INTO Localidades VALUES('BO','04','05','05','SALINAS DE GARCÍ MENDOZA')
INSERT INTO Localidades VALUES('BO','04','06','06','HUACHACALLA')
INSERT INTO Localidades VALUES('BO','04','07','07','LA RIVERA')
INSERT INTO Localidades VALUES('BO','04','08','08','HUAYLLAMARCA')
INSERT INTO Localidades VALUES('BO','04','09','09','HUANUNI')
INSERT INTO Localidades VALUES('BO','04','10','10','POOPÓ')
INSERT INTO Localidades VALUES('BO','04','11','11','CURAHUARA DE CARANGAS')
INSERT INTO Localidades VALUES('BO','04','12','12','TOTORA')
INSERT INTO Localidades VALUES('BO','04','13','13','TOLEDO')
INSERT INTO Localidades VALUES('BO','04','14','14','SANTIAGO DE HUARI')
INSERT INTO Localidades VALUES('BO','04','15','15','SANTIAGO DE ANDAMARCA')
INSERT INTO Localidades VALUES('BO','04','16','16','EUCALIPTUS')


--LOCALIDADES DE POTOSÍ
INSERT INTO Localidades VALUES('BO','05','01','01','SACACA')
INSERT INTO Localidades VALUES('BO','05','02','02','UYUNI')
INSERT INTO Localidades VALUES('BO','05','03','03','ARAMPAMPA')
INSERT INTO Localidades VALUES('BO','05','04','04','SAN PEDRO DE BUENA VISTA')
INSERT INTO Localidades VALUES('BO','05','05','05','COLQUECHACA')
INSERT INTO Localidades VALUES('BO','05','06','06','BETANZOS')
INSERT INTO Localidades VALUES('BO','05','07','07','LLICA')
INSERT INTO Localidades VALUES('BO','05','08','08','SAN AGUSTÍN')
INSERT INTO Localidades VALUES('BO','05','09','09','PUNA')
INSERT INTO Localidades VALUES('BO','05','10','10','VILLAZÓN')
INSERT INTO Localidades VALUES('BO','05','11','11','COTAGAITA')
INSERT INTO Localidades VALUES('BO','05','12','12','COLCHA K')
INSERT INTO Localidades VALUES('BO','05','13','13','UNCÍA')
INSERT INTO Localidades VALUES('BO','05','14','14','TUPIZA')
INSERT INTO Localidades VALUES('BO','05','15','15','SAN PABLO DE LÍPEZ')
INSERT INTO Localidades VALUES('BO','05','16','16','POTOSÍ')


--LOCALIDADES DE TARIJA
INSERT INTO Localidades VALUES('BO','06','01','01','PADCAYA')
INSERT INTO Localidades VALUES('BO','06','02','02','ENTRE RÍOS')
INSERT INTO Localidades VALUES('BO','06','03','03','TARIJA ')
INSERT INTO Localidades VALUES('BO','06','04','04','SAN LORENZO')
INSERT INTO Localidades VALUES('BO','06','05','05','YACUIBA')
INSERT INTO Localidades VALUES('BO','06','06','06','URIONDO')


--LOCALIDADES DE SANTA CRUZ
INSERT INTO Localidades VALUES('BO','07','01','01','SANTA CRUZ DELA SIERRA')
INSERT INTO Localidades VALUES('BO','07','02','02','SAN MATÍAS')
INSERT INTO Localidades VALUES('BO','07','03','03','COMARAPA')
INSERT INTO Localidades VALUES('BO','07','04','04','SAN JOSÉ DE CHIQUITOS')
INSERT INTO Localidades VALUES('BO','07','05','05','LAGUNILLAS')
INSERT INTO Localidades VALUES('BO','07','06','06','SAMAIPATA')
INSERT INTO Localidades VALUES('BO','07','07','07','PUERTO SUÁREZ')
INSERT INTO Localidades VALUES('BO','07','08','08','ASCENSIÓN')
INSERT INTO Localidades VALUES('BO','07','09','09','BUENA VISTA')
INSERT INTO Localidades VALUES('BO','07','10','10','CONCEPCIÓN')
INSERT INTO Localidades VALUES('BO','07','11','11','MONTERO')
INSERT INTO Localidades VALUES('BO','07','12','12','PORTACHUELO')
INSERT INTO Localidades VALUES('BO','07','13','13','VALLEGRANDE')
INSERT INTO Localidades VALUES('BO','07','14','14','SAN IGNACIO DE VELASCO')
INSERT INTO Localidades VALUES('BO','07','15','15','WARNES')


--LOCALIDADES DE BENI
INSERT INTO Localidades VALUES('BO','08','01','01','SAN JAVIER')
INSERT INTO Localidades VALUES('BO','08','02','02','RIBERALTA')
INSERT INTO Localidades VALUES('BO','08','03','03','SANTOS REYES')
INSERT INTO Localidades VALUES('BO','08','04','04','SANTA ANA DEL YACUMA')
INSERT INTO Localidades VALUES('BO','08','05','05','SAN IGNACIO DE MOXOS')
INSERT INTO Localidades VALUES('BO','08','06','06','LORETO')
INSERT INTO Localidades VALUES('BO','08','07','07','SAN JOAQUÍN')
INSERT INTO Localidades VALUES('BO','08','08','08','MAGDALENA')


--LOCALIDADES DE PANDO
INSERT INTO Localidades VALUES('BO','09','01','01','SANTA ROSA DE ABUNÁ')
INSERT INTO Localidades VALUES('BO','09','02','02','FORTALEZA')
INSERT INTO Localidades VALUES('BO','09','03','03','PUERTO GONZALO MORENO')
INSERT INTO Localidades VALUES('BO','09','04','04','PUERTO RICO')
INSERT INTO Localidades VALUES('BO','09','05','05','PORVENIR')

----NOMBRES DE UNIDADES MEDICAS
--INSERT INTO dbo.UnidadesMedicas VALUES('INSTITUTO NACIONAL DE PSIQUIATRÍA GREGORIO PACHECO','','64-55897','')
--INSERT INTO dbo.UnidadesMedicas VALUES('HOSPITAL SANTA BÁRBARA','','64-60133','')
--INSERT INTO dbo.UnidadesMedicas VALUES('INSTITUTO DE GASTROENTEROLOGÍA BOLIVIANO JAPONÉS','','64-54700','')
--INSERT INTO dbo.UnidadesMedicas VALUES('INSTITUTO PSICOPEDAGÓGICO SAN JUAN DE DIOS','','','')
--INSERT INTO dbo.UnidadesMedicas VALUES('HOSPITAL CRISTO DE LAS AMÉRICAS','','64-43269','')
--INSERT INTO dbo.UnidadesMedicas VALUES('HOSPITAL GINECO-OBSTÉTRICO','','64-44644','')
--INSERT INTO dbo.UnidadesMedicas VALUES('CAJA NACIONAL DE SALUD','','','')



----FUNCIONARIAS DEL DEPARTAMENTO DE TRABAJO SOCIAL EN LA TABLA DE USUARIO
--INSERT INTO dbo.Usuarios VALUES('administrador','administrador','EDITH','VILLCA','TICONA','5655076','Raul Romero Linares Nro. D-2','64-28517','76127784','A','1')
--INSERT INTO dbo.Usuarios VALUES('silvia','trabajosocial','LIC. SILVIA','ZAMORA','ROMERO','1099141','Serrano Nro. 268','64-41067','79301345','T','1')
--INSERT INTO dbo.Usuarios VALUES('silvia','trabajosocial','LIC. ELIZABETH ','VILLAGOMEZ','PANIAGUA','1093814','Lima Pampa Nro. 32','64-44489','','T','1')




----NOMBRES DE DOCUMENTOS
--INSERT INTO dbo.DocumentosTipo VALUES('CERTIFICADO DE NACIMIENTO','')
--INSERT INTO dbo.DocumentosTipo VALUES('CARNET DE IDENTIDAD','')
--INSERT INTO dbo.DocumentosTipo VALUES('CERTIFICADO DE BAUTIZO','')
--INSERT INTO dbo.DocumentosTipo VALUES('CARNET DE ASEGURADO','')


----NOMBRES DE PARENTESCO
--INSERT INTO dbo.Parentescos VALUES('PADRE','')
--INSERT INTO dbo.Parentescos VALUES('MADRE','')
--INSERT INTO dbo.Parentescos VALUES('SUEGRO(A)','')
--INSERT INTO dbo.Parentescos VALUES('HIJO(A)','')
--INSERT INTO dbo.Parentescos VALUES('YERNO','')
--INSERT INTO dbo.Parentescos VALUES('NUERA','')
--INSERT INTO dbo.Parentescos VALUES('ABUELO(A)','')
--INSERT INTO dbo.Parentescos VALUES('HERMANO(A)','')
--INSERT INTO dbo.Parentescos VALUES('CUÑADO(A)','')
--INSERT INTO dbo.Parentescos VALUES('NIETO(A)','')
--INSERT INTO dbo.Parentescos VALUES('BISABUELO(A)','')
--INSERT INTO dbo.Parentescos VALUES('TÍO(A)','')
--INSERT INTO dbo.Parentescos VALUES('SOBRINO(A)','')
--INSERT INTO dbo.Parentescos VALUES('BIZNIETO(A)','')
--INSERT INTO dbo.Parentescos VALUES('PRIMO(A)','')
--INSERT INTO dbo.Parentescos VALUES('AMIGO(A)','')


----NOMBRES DE TIPOS DE ACTIVIDADES
--INSERT INTO dbo.ActividadesTipo VALUES('INGRESOS - REINGRESOS','')
--INSERT INTO dbo.ActividadesTipo VALUES('FICHA SOCIAL - H.CLINICA','')
--INSERT INTO dbo.ActividadesTipo VALUES('ORIENTACIÓN','')
--INSERT INTO dbo.ActividadesTipo VALUES('COORDINACIÓN INTERINSTITUCIONAL','')
--INSERT INTO dbo.ActividadesTipo VALUES('COORDINACIÓN INTRAINSTITUCIONAL','')
--INSERT INTO dbo.ActividadesTipo VALUES('ENTREVISTA CON PACIENTES','')
--INSERT INTO dbo.ActividadesTipo VALUES('ENTREVISTA CON FAMILIARES O RESPONSABLE','')
--INSERT INTO dbo.ActividadesTipo VALUES('VISITA DOMICILIARIA','')
--INSERT INTO dbo.ActividadesTipo VALUES('GESTIÓN INTERCONSULTA','')
--INSERT INTO dbo.ActividadesTipo VALUES('GESTIÓN DE RECETA','')
--INSERT INTO dbo.ActividadesTipo VALUES('GESTION DE LABORATORIO','')
--INSERT INTO dbo.ActividadesTipo VALUES('OTROS TRÁMITES','')
--INSERT INTO dbo.ActividadesTipo VALUES('ALTAS','')
--INSERT INTO dbo.ActividadesTipo VALUES('EVACIÓN','')
--INSERT INTO dbo.ActividadesTipo VALUES('DEFUNCIÓN','')
--INSERT INTO dbo.ActividadesTipo VALUES('COORDINACIÓN CON JEFE DE UNIDAD','')
--INSERT INTO dbo.ActividadesTipo VALUES('COORDINACIÓN .......','')
--INSERT INTO dbo.ActividadesTipo VALUES('REUNIÓN CON EQUIPO','')
--INSERT INTO dbo.ActividadesTipo VALUES('CONFERENCIAS O CAPACITACIÓN','')
--INSERT INTO dbo.ActividadesTipo VALUES('SESIÓN CLÍNICA','')



--select * from usuarios
--select * from productostipos